version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-analytics-tool
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - /app/venv
    env_file:
      - .env
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
